name: Continuous Deployment

on:
  push:
    branches: master

jobs:
  deploy-to-npm:
    name: Deploy to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Build
        run: |
          yarn install --frozen-lock --non-interactive
          yarn prepublish
      - name: npm publish on every push
        uses: shawnbot/npm-publish-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
