name: Continuous Deployment

on:
  push:
    branches: master

jobs:
  build-and-deloy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container: node:12.8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build
        run: |
          npm ci
          npm build:npm
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_NPM_READ }}
        run: |
          yarn config set "@open-columnist:registry" "https://npm.pkg.github.com:_authToken=${GITHUB_TOKEN}"
          yarn publish
