name: Continuous Deployment

on:
  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:12.8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build
        run: |
          npm ci
          npm run build:npm
