name: Continuous Deployment

on:
  push:
    branches: master

jobs:
  build-and-deloy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container: node:12.8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build & Publish
        run: |
          npm ci
          npm build:npm
